#ifndef eien65_shared_enums_h
#define eien65_shared_enums_h

enum error_msg_t {
    UNINITIALIZED,
    INDEX_OUT_OF_BOUNDS,
    BUFFER_FULL,
    INCORRECT_PARITY,
    INVALID_STATE,
	UNKNOWN_COMMAND,
    BAD_ENCODER_INTERRUPT,
    UNHANDLED_CASE,
    OVERFLOW
};
enum msg_avr_to_pc_t {
	INVALID_MSG_AVR,
    ERROR,
    ECHO_REPLY,
	RECEIVED_HEADER,
	RECEIVED_DATA,
	RECEIVED_PARITY,
    BTN_STATUS,
    POTENTIOMETER_STATUS,
    CURRENT_STATE,
    SPEED_H,
    SPEED_L,
    AVG_TIME_H,
    AVG_TIME_L,
    WAKE_UP_TIME_H,
    WAKE_UP_TIME_L,
    INTERRUPT_TIME_H,
    INTERRUPT_TIME_L,
    WHICH_INTERRUPT,
    GOOD_INTERRUPTS,
    BAD_INTERRUPTS
};
enum msg_pc_to_avr_t {
	INVALID_MSG_PC,
    ECHO,
    SET_STATE_NONE,
    GET_STATE,
    START_BLINK_LED,
    STOP_BLINK_LED,
    START_REPORT_BTNS,
    STOP_REPORT_BTNS,
    START_REPORT_POTENTIOMETER,
    STOP_REPORT_POTENTIOMETER,
    READ_BTNS,
    READ_POTENTIOMETER,
    TURN_ON_LED,
    TURN_OFF_LED,
    SET_PWM1,
    SET_PWM2,
    GET_SPEED,
    GET_AVG_TIME,
    GET_INTERRUPT_STATS,
    GET_RECENT_TIMES
};
enum state_t {
    STATE_NONE,
    STATE_FIXED_PWM,
    STATE_SPEED_CONTROL,
    STATE_POSITION_CONTROL
};

#endif
